
version: "3.7"

services:
  papermerge:
    image: linuxserver/papermerge:version-v1.5.5
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Berlin
    volumes:
      - conf_09_dms_config:/config
      - conf_09_dms_data:/data
#    ports:
#      - 8000:8000
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    
volumes:
  conf_09_dms_config:
    external: true
  conf_09_dms_data:
    external: true
