version: "3.7"

services:
  nginx:
    image: ghcr.io/linuxserver/nginx
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./proxy:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - proxy

  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall:/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
