version: "3.7"

services:
  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Berlin
    volumes:
      - /bdcloud/conf_05_DLNA:/config
      - /bdcloud/vol_smb_Video:/data/tvshows
      - /bdcloud/vol_smb_Audio:/data/tvshows
      - /bdcloud/vol_smb_Pictures:/data/tvshows
      - /bdcloud/vol_smb_TV:/data/tvshows
#      - /opt/vc/lib:/opt/vc/lib #optional
#    ports:
#      - 8096:8096
#      - 8920:8920 #optional
#    devices:
#      - /dev/dri:/dev/dri #optional
#      - /dev/vchiq:/dev/vchiq #optional
#      - /dev/video10:/dev/video10 #optional
#      - /dev/video11:/dev/video11 #optional
#      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true

