version: "3.7"

services:
  emby:
    image: linuxserver/emby:version-4.5.4.0
    container_name: emby
    environment:
      - PUID=1000
      - PGID=998
      - TZ=Europe/Berlin
    volumes:
      - conf_10_dlna:/config:z # :z allows share to be used by multiple containers
#      - /bdcloud/vol_smb_Video:/data/tvshows:z # :z allows share to be used by multiple containers
#      - /bdcloud/vol_smb_Audio:/data/tvshows:z # :z allows share to be used by multiple containers
#      - /bdcloud/vol_smb_Pictures:/data/tvshows:z # :z allows share to be used by multiple containers
#      - /bdcloud/vol_smb_tv:/data/tvshows:z # :z allows share to be used by multiple containers
#      - /opt/vc/lib:/opt/vc/lib #optional
      - smb_video:/opt/video:z # :z allows share to be used by multiple containers
      - smb_audio:/opt/audio:z # :z allows share to be used by multiple containers
      - smb_pictures:/opt/pictures:z # :z allows share to be used by multiple containers
      - smb_tv:/opt/tv:z # :z allows share to be used by multiple containers
#    ports:
#      - 8096:8096
#      - 8920:8920 #optional
#    devices:
#      - /dev/dri:/dev/dri #optional
#      - /dev/vchiq:/dev/vchiq #optional
#      - /dev/video10:/dev/video10 #optional
#      - /dev/video11:/dev/video11 #optional
#      - /dev/video12:/dev/video12 #optional
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    
volumes:
  conf_10_dlna:
    external: true
  smb_video:
    external: true
  smb_audio:
    external: true
  smb_pictures:
    external: true
  smb_tv:
    external: true 
