version: "3.7"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.6
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=pass  # hier euer Passwort eingeben
    # Volumes store your data between container upgrades
    volumes:
      - conf_02_pihole:/etc/pihole/
      - conf_02_pihole_dns:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  conf_02_pihole:
    external: true
  conf_02_pihole_dns:
    external: true
