version: "3.7"

services:
  wp1:
    image: linuxserver/nginx:amd64-version-8349a582
    container_name: wp1
    depends_on:
      - "mariadb_wp1"
    environment:
      # User (Docker User) und Gruppen (Docker Gruppe) anpassen
      - PUID=1000
      - PGID=998
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=USER_DB_NAME #optional
      - MYSQL_USER=MYSQL_USER #optional
      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
    volumes:
      - conf_14_wp1_data:/var/www/html/wp-content
      - conf_14_wp1_config:/config
    restart: unless-stopped
    networks:
      - proxy
      

  mariadb_wp1:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb_wp1
    environment:
      - PUID=1000
      - PGID=998
      - MYSQL_ROOT_PASSWORD=ROOT_ACCESS_PASSWORD
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=USER_DB_NAME #optional
      - MYSQL_USER=MYSQL_USER #optional
      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
    volumes:
      - conf_14_wp1_db:/config
    restart: unless-stopped      
